language: php
dist: trusty

php:
- 7.1
- 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- composer validate --strict
- find src tests -name '*.php' | xargs -n 1 -P4 php -l
- vendor/bin/phpunit --fail-on-risky
